# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Numbers API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for Numbers API
pod 'Alamofire’,'~> 4.5.1’
end

  target 'Numbers APITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Numbers APIUITests' do
    # Pods for testing
end